language: android
jdk:
  - oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - extra-android-m2repository
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
before_script:
  - mkdir -p $ANDROID_HOME/licenses
  - echo $android_sdk_license > $ANDROID_HOME/licenses/android-sdk-license
script:
  - ./gradlew dtglib:build dtgapp:build
before_deploy:
  - mv dtglib/build/intermediates/bundles/release/classes.jar dtglib-$TRAVIS_TAG.jar
deploy:
  provider: releases
  draft: false
  skip_cleanup: true
  file:
    - dtglib-$TRAVIS_TAG.jar
  on:
    tags: true
  api-key: $GH_TOKEN
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
    on_success: change
    on_failure: always
